cosmos/interchain-accounts-demo

app/app.go
init.sh
rly/interchain-acc-config/chains/test-1.json
rly/interchain-acc-config/chains/test-2.json
rly/interchain-acc-config/paths/test1-account-test2.json
rly/interchain-acc-config/rly.sh

Adding scripts to start up multiple blockchains with a relayer. 
Run the blockchains with `init.sh` and add the mnemonics to the `rly.sh` script. 
Example output of the relayer running with both chains:

adding init.sh for multiple chains and relayer script

---

go.mod
go.sum
network/relayer/interchain-acc-config/rly.sh
x/ibc-account/keeper/relay.go

Bumping the SDK version and using the most recent relayer commands in `rly.sh`. 
This PR depends on https://github.com/cosmos/relayer/pull/483

fix(timeoutHeight): removing ZeroHeight() and bumping sdk version, fixing rly.sh

---

network/hermes/README.md
network/hermes/config.toml
network/hermes/hermes.sh
network/init.sh
x/ibc-account/keeper/relay.go

The following PR adds a basic Hermes relayer configuration and associated initialisation script for creation of client, connection and channel entities used by the IBC protocol to handle packet relaying between IBC enabled chains.
Please see network/hermes/README.md for prerequisite info.
This PR includes a minor change to `timeoutTimestamp` whereby the unsigned bit is shifted to the right, allowing for the Hermes relayer to successfully relay packets and avoid overflow when Hermes performs timestamp conversion.
See: https://github.com/informalsystems/ibc-rs/blob/master/modules/src/timestamp.rs#L46
```
WARN ibc_relayer::event::rpc: error while building event send_packet.packet_data
WARN ibc_relayer::event::rpc: error while building event Error converting from u64 to i64: out of range …
```

Hermes relayer integration

---

Makefile
network/hermes/hermes-restore-key.sh
network/hermes/hermes.sh
network/hermes/start.sh
network/init.sh
network/start.sh

Updating the dev-environment to use the hermes relayer as a default. 
`make init` 
This will start two chains locally and start the hermes relayer. It will configure a client, connection and create an ics20 & ics27 channel on the same connection. 
`make init-golang-rly` 
This is a legacy command for running the dev-environment with the golang relayer.

feat(hermes-relayer):updating makefile to use hermes relayer as default

---

readme.md

* Change git clone command to use https url instead of ssh (If user doesn't set ssh key for github account, it will fail.)
* Fix the path for cloned git repo

doc: Update readme.md

---

app/app.go
x/ibc-account/keeper/keeper.go
x/ibc-account/keeper/relay.go

Removing the tx encoder step. For now, we will only support cosmos SDK chains. We can add this functionality later if necessary.
Depends on: https://github.com/cosmos/interchain-accounts/pull/52

fix: removing tx encoder

---

README.md

updating docs to include commit hash of working branch for hermes binary.

docs: adding commit hash for working version of hermes

---

app/app.go
x/inter-tx/keeper/keeper_test.go
x/inter-tx/keeper/msg_server.go
x/inter-tx/keeper/msg_server_test.go

- Adding tests for msg_server `Register`
- Adding helper functions for accessing ICAApp & path setup
- Updating App to correctly expose `interTxKeeper`

test: adding tests for msg server register account

---

README.md

Updating the readme to use a temp fork of the hermes repo while we work on the version string update. (adis branch is no longer working).

fix: add new hermes repo

---

app/app.go

Fixes a bug whereby exporting genesis state to JSON with `icad export` would cause a panic due to a nil store key for `x/feegrant`. Identified while reproducing [ibc-go-673](https://github.com/cosmos/ibc-go/issues/673).
- adding feegrant store key to resolve panic on export genesis

fix: resolve icad export panic (genesis)

---

README.md
go.mod
go.sum
x/inter-tx/ibc_module.go
x/inter-tx/keeper/msg_server.go

- Update ibc-go dependency to `v3.0.0-rc2`
- Update `README.md` to include Hermes `v0.13.0-rc0`
- Adding timeout to `SendTx`
- Adding timeout scenario test to `README.md`

chore: update to v3.0.0-rc2 and hermes v0.13.0-rc0

---

.github/workflows/docker-build-fork.yml
.github/workflows/docker-build.yml

Forks do not have access to secrets and so are unable to build and push to the ghcr registry.
We can skip this workflow if that is case.
An additional basic docker build task which runs only on forks is added. This ensures that the image builds successfully, but we are not pushing it anywhere.
To verify the task I ran the command `docker build . --no-cache` locally and it succeeds.

Updating docker build action to skip on forks

---

x/inter-tx/keeper/msg_server.go

- use ctx.BlockTime() in favour of time.Now() to allow multiple nodes in e2e tests

fix: use ctx.BlockTime() in favour of time.Now()

---

x/inter-tx/types/codec.go

This PR fixes the wrong registration for the Amino types of both `MsgRegisterAccount` and `MsgSubmitTx`. 
Previously messages were registered as objects, instead of pointers. This caused them to be impossible to deserialize using the `UnmarshalJSON` method due to the following error: 
```
reflect.Set: value of type types.MsgXXXXX is not assignable to type types.Msg
```
Registering them as pointers fixes this error.

fix: wrong Amino concrete type registration

---

.github/workflows/build-icad-image-from-tag.yml

This workflow allows us to manually build a Docker image my specifying the desired tag.
Almost identical to the one we have in `ibc-go` to build simd images.

Adding workflow to manually build image from tags

---

.github/workflows/build-icad-image-from-tag.yml

The build failed as the `Makefile` is also required.
I tested on this branch and the [task succeeded](https://github.com/cosmos/interchain-accounts-demo/runs/7858650888?check_suite_focus=true)

Adding missing makefile in github workflow

---

x/inter-tx/keeper/msg_server.go

I was working on an ICA test case in `ibctest` and noticed that packets were no longer timing out as expected. After digging into the issue some more I noticed that in #108 the timeout offset was changed from one minute to one hour.

fix: change timeout offset from 1 hour to 1 minute

---

x/inter-tx/ibc_module.go
x/inter-tx/keeper/keeper.go

- Logs the response data using the sdk v0.46 `MsgResponses` encoded Anys
- Adding the sdk v0.45 handling of `stakingtypes.MsgDelegateResponse` in `msgData.Data`
Example Logs:
- `MsgDelegateResponse`
```
{"level":"info","module":"x/intertx","response":"&Any{TypeUrl: \"/cosmos.staking.v1beta1.MsgDelegateResponse\",\n  Value: []byte(nil)\n}","typeURL":"/cosmos.staking.v1beta1.MsgDelegateResponse","time":"2022-08-22T15:15:54+02:00","message":"msg response in ICS-27 packet"}
```
- `MsgSendResponse`
```
{"level":"info","module":"x/intertx","response":"&Any{TypeUrl: \"/cosmos.bank.v1beta1.MsgSendResponse\",\n  Value: []byte(nil)\n}","typeURL":"/cosmos.bank.v1beta1.MsgSendResponse","time":"2022-08-22T15:16:01+02:00","message":"msg response in ICS-27 packet"}
```
Both response data values are …

chore: log response data from 0.46 sdk

---

.github/mergify.yml

- Adding `mergify.yml` to `.github`
- Adding backport rules for:
- Release branch `release/v0.1.x` (ibc-go/v3)
- Release branch `release/v0.2.x` (ibc-go/v4)
- Release branch `release/v0.3.x` (ibc-go/v5)

chore: adding mergify.yml with backport rules

---

app/app.go

Required for running upgrades in e2e.
Module version map must be set in pre-upgrade chain state.
See: https://github.com/cosmos/cosmos-sdk/blob/v0.46.1/types/module/module.go#L393-L401
Follow up tasks:
- Merge main to `release/v0.3.x`
- Tag `v0.3.5` and build docker image

fix: set module version map in `InitChainer`

---

app/app.go
app/upgrades/v6/upgrades.go
go.mod
go.sum
x/inter-tx/ibc_module.go
x/inter-tx/keeper/grpc_query.go
x/inter-tx/keeper/keeper.go
x/inter-tx/keeper/keeper_test.go
x/inter-tx/keeper/msg_server.go
x/inter-tx/keeper/msg_server_test.go
x/inter-tx/types/msgs_test.go

- Upgrading `ibc-go` to `v6.0.0-alpha1`
- Adding `ibc-go/v6` upgrade handler to `app`
- Removing claiming on channel capability in `intertx` handshake callback `OnChanOpenInit`
- Removing lookup of channel capability in `intertx/SubmitTx` handler
Follow up tasks:
- Cut `release/0.4.x` branch for `ibc-go/v6` line
- Tag `v0.4.0` and build docker image

deps: upgradingto ibc-go v6-alpha1
